# Generated by Django 3.2.13 on 2022-06-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='adress',
            new_name='address',
        ),
    ]
