# Generated by Django 3.2.13 on 2022-06-15 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_rename_adress_advertisement_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
